hash-format = "sha256"

[[files]]
file = "README.md"

[[files]]
file = "index.html"

[[files]]
file = "mods/ad-astra.pw.toml"
metafile = true

[[files]]
file = "mods/adopt-a-floppa.pw.toml"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
metafile = true

[[files]]
file = "mods/another-furniture.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
metafile = true

[[files]]
file = "mods/arcanus.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/astral-additions-for-create-astral.pw.toml"
metafile = true

[[files]]
file = "mods/astral-vinery.pw.toml"
metafile = true

[[files]]
file = "mods/audio-extension-for-fancymenu-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/auto-config-updated-api.pw.toml"
metafile = true

[[files]]
file = "mods/automobility.pw.toml"
metafile = true

[[files]]
file = "mods/auudio-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/balm-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/better-combat-by-daedelus.pw.toml"
metafile = true

[[files]]
file = "mods/biomesyougo.pw.toml"
metafile = true

[[files]]
file = "mods/cammies-wearable-backpacks.pw.toml"
metafile = true

[[files]]
file = "mods/campanion.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components.pw.toml"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
metafile = true

[[files]]
file = "mods/catwalks-inc.pw.toml"
metafile = true

[[files]]
file = "mods/cc-restitched.pw.toml"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/chassis.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
metafile = true

[[files]]
file = "mods/chunky-pregenerator.pw.toml"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/cobblegen.pw.toml"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
metafile = true

[[files]]
file = "mods/companion-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/completeconfig.pw.toml"
metafile = true

[[files]]
file = "mods/compressor.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/cooking-for-blockheads-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/coyote-time.pw.toml"
metafile = true

[[files]]
file = "mods/create-deco-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-extended-flywheels-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-sifting-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
metafile = true

[[files]]
file = "mods/ctm-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
metafile = true

[[files]]
file = "mods/custom-machinery.pw.toml"
metafile = true

[[files]]
file = "mods/datapack-portals.pw.toml"
metafile = true

[[files]]
file = "mods/daves-building-extended-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/disable-villager-trades.pw.toml"
metafile = true

[[files]]
file = "mods/disco.pw.toml"
metafile = true

[[files]]
file = "mods/drink-beer-unofficial-clockwerk-edition.pw.toml"
metafile = true

[[files]]
file = "mods/drippy-loading-screen-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/drp-global-datapack.pw.toml"
metafile = true

[[files]]
file = "mods/dustrial-decor-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/environmental-creepers.pw.toml"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
metafile = true

[[files]]
file = "mods/extractinator.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-disable-custom-worlds-advice.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fabrictailor.pw.toml"
metafile = true

[[files]]
file = "mods/falling-leaves-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/fancymenu-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/fast-furnace-for-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-backups-2.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-library-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-quests-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-teams-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/gearreborn.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/harvest-with-ease.pw.toml"
metafile = true

[[files]]
file = "mods/hephaestus-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/iceberg-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/idwtialsimmoedm.pw.toml"
metafile = true

[[files]]
file = "mods/ignore me"

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/item-filters.pw.toml"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/konkrete-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs-create.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
metafile = true

[[files]]
file = "mods/leashable-players.pw.toml"
metafile = true

[[files]]
file = "mods/leaves-us-in-peace.pw.toml"
metafile = true

[[files]]
file = "mods/let-me-despawn.pw.toml"
metafile = true

[[files]]
file = "mods/lets-do-wine.pw.toml"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
metafile = true

[[files]]
file = "mods/limited-chunkloading.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/load-my-resources-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/lootr-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/mcdw.pw.toml"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
metafile = true

[[files]]
file = "mods/mobvotes-sniffer.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
metafile = true

[[files]]
file = "mods/mystical-oak-tree.pw.toml"
metafile = true

[[files]]
file = "mods/naturalist.pw.toml"
metafile = true

[[files]]
file = "mods/numeral-ping.pw.toml"
metafile = true

[[files]]
file = "mods/observable.pw.toml"
metafile = true

[[files]]
file = "mods/oh-the-biomes-youll-go-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
metafile = true

[[files]]
file = "mods/packages.pw.toml"
metafile = true

[[files]]
file = "mods/packed-inventory.pw.toml"
metafile = true

[[files]]
file = "mods/passive-piglins.pw.toml"
metafile = true

[[files]]
file = "mods/per-aspera.pw.toml"
metafile = true

[[files]]
file = "mods/pettable.pw.toml"
metafile = true

[[files]]
file = "mods/phonos.pw.toml"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
metafile = true

[[files]]
file = "mods/polaroid-camera.pw.toml"
metafile = true

[[files]]
file = "mods/polymorph-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/projectile-damage-attribute.pw.toml"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/quarry-reborn.pw.toml"
metafile = true

[[files]]
file = "mods/quests-additions-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/reinforced-chests.pw.toml"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
metafile = true

[[files]]
file = "mods/save-and-load-inventories.pw.toml"
metafile = true

[[files]]
file = "mods/searchlight.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/servertick.pw.toml"
metafile = true

[[files]]
file = "mods/show-me-what-you-got.pw.toml"
metafile = true

[[files]]
file = "mods/slideshow-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/smooth-boot.pw.toml"
metafile = true

[[files]]
file = "mods/smooth-chunk-save.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
metafile = true

[[files]]
file = "mods/subterrestrial.pw.toml"
metafile = true

[[files]]
file = "mods/suggestion-tweaker.pw.toml"
metafile = true

[[files]]
file = "mods/techreborn.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/wi-zoom.pw.toml"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/xl-packets-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/youre-in-grave-danger.pw.toml"
metafile = true
